"""Create crypto tables

Revision ID: db7e229055b1
Revises: 20231005_crypto
Create Date: 2025-03-10 07:51:31.137424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7e229055b1'
down_revision = '20231005_crypto'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_data', schema=None) as batch_op:
        batch_op.alter_column('cryptocurrency_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_data', schema=None) as batch_op:
        batch_op.alter_column('cryptocurrency_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
